#!/bin/sh

## EDIT THESE
GRAPHARG="/home/rac101/storage/files/cs/argumentation/code/grapharg/code/grapharg.pl"
SICSTUS="/usr/local/sicstus4.2.0/bin/sicstus"
## END OF EDITS

CLAIM=""
DERIVEGOAL=""
DIR=`pwd`
FILE=""
GETCLAIM=0
GETSTRATEGY=0
GOALFLAG="--goal"
PREDICATE=""
PROLOG=${SICSTUS}
PROLOGQUIET="--noinfo --nologo"
QUIET=0
SCRIPTSTYLE=0
STRATEGY=""

## get command line arguments

ARGNUM=0
for ARG in "$@"
do
 ARGNUM=`expr $ARGNUM + 1`
 if [ $ARG = "-r" ]; then
  SCRIPTSTYLE=1
 else
  if [ $ARG = "-q" ]; then
   QUIET=1
  else
   if [ $ARG = "-c" ]; then
    GETCLAIM=1
   else
    if [ $ARG = "-s" ]; then
     GETSTRATEGY=1
    else
     if [ $GETCLAIM -eq 1 ]; then
      CLAIM=$ARG
      GETCLAIM=0
     else
      if [ $GETSTRATEGY -eq 1 ]; then
       STRATEGY=$ARG
       GETSTRATEGY=0
      else
       FILE=`echo "$ARG" | sed 's/\.pl$//'`
      fi
     fi
    fi
   fi
  fi
 fi
done

if [ $SCRIPTSTYLE -eq 0 ]; then
 if [ -z $FILE ]; then
  GOAL="set_opt(frameworkdir,'${DIR}/')."
 else
  GOAL="set_opt(frameworkdir,'${DIR}/'),loadf(${FILE})."
 fi
 rlwrap ${PROLOG} -l ${GRAPHARG} ${GOALFLAG} "${GOAL}"
else
 if [ $QUIET -eq 0 ]; then
  PREDICATE="script_derive_print"
 else
  PREDICATE="script_derive"
 fi
 if [ -z $STRATEGY ]; then
  DERIVEGOAL="${PREDICATE}(${CLAIM})"
 else
  DERIVEGOAL="${PREDICATE}(${CLAIM},${STRATEGY})"
 fi
 GOAL="set_opt(frameworkdir,'${DIR}/'),loadf(${FILE}),${DERIVEGOAL},halt."
 ${PROLOG} -l ${GRAPHARG} ${PROLOGQUIET} ${GOALFLAG} "${GOAL}"
fi

